package com.truckmovement.mvvm.ui.loadinginformation.addspinnerdata

import com.truckmovement.mvvm.ui.loadinginformation.model.FromTypeModel


class FromSpinnerData {
    fun addFromDat(list:ArrayList<FromTypeModel>){
        list.add(FromTypeModel("MUC",1))
        list.add(FromTypeModel("NUE",2))
        list.add(FromTypeModel("STR",3))
        list.add(FromTypeModel("CGN",4))
        list.add(FromTypeModel("DUS",5))
        list.add(FromTypeModel("FMO",6))
        list.add(FromTypeModel("HAJ",7))
        list.add(FromTypeModel("BRE",8))
        list.add(FromTypeModel("HAM",9))
        list.add(FromTypeModel("TXL",10))
        list.add(FromTypeModel("LEJ",11))
        list.add(FromTypeModel("DRS",12))
        list.add(FromTypeModel("LHR",13))
        list.add(FromTypeModel("MAN",14))
        list.add(FromTypeModel("DUB",15))
        list.add(FromTypeModel("GLA",16))
        list.add(FromTypeModel("LUX",17))
        list.add(FromTypeModel("LGG",18))
        list.add(FromTypeModel("GOT",19))
        list.add(FromTypeModel("CHP",20))
        list.add(FromTypeModel("OSL",21))
        list.add(FromTypeModel("BLL",22))
        list.add(FromTypeModel("MMX",23))
        list.add(FromTypeModel("ARN",24))
        list.add(FromTypeModel("AMS",25))
        list.add(FromTypeModel("MST",26))
        list.add(FromTypeModel("RTM",27))
        list.add(FromTypeModel("EIN",28))
        list.add(FromTypeModel("BRU",29))
        list.add(FromTypeModel("CDG",30))
        list.add(FromTypeModel("ORY",31))
        list.add(FromTypeModel("TLS",32))
        list.add(FromTypeModel("NTE",33))
        list.add(FromTypeModel("MRS",34))
        list.add(FromTypeModel("MLH",35))
        list.add(FromTypeModel("LIL",36))
        list.add(FromTypeModel("NCE",37))
        list.add(FromTypeModel("GVA",38))
        list.add(FromTypeModel("VIE",39))
        list.add(FromTypeModel("BRN",40))
        list.add(FromTypeModel("SZG",41))
        list.add(FromTypeModel("INN",42))
        list.add(FromTypeModel("LNZ",43))
        list.add(FromTypeModel("GRZ",44))
        list.add(FromTypeModel("SOF",45))
        list.add(FromTypeModel("ZAZ",46))
        list.add(FromTypeModel("MAD",47))
        list.add(FromTypeModel("BCN",48))
        list.add(FromTypeModel("VLC",49))
        list.add(FromTypeModel("OTP",50))
        list.add(FromTypeModel("BTS",51))
        list.add(FromTypeModel("BEG",52))
        list.add(FromTypeModel("ZRH",53))
        list.add(FromTypeModel("BSL",54))
        list.add(FromTypeModel("MIL",55))
        list.add(FromTypeModel("FCO",56))
        list.add(FromTypeModel("PRG",57))
        list.add(FromTypeModel("HHN",58))
        list.add(FromTypeModel("BUD",59))
        list.add(FromTypeModel("WAW",60))
        list.add(FromTypeModel("FRA",61))
        list.add(FromTypeModel("SCN",62))
        list.add(FromTypeModel("SXB",63))
    }
}